// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XLWebServices.Data;

#nullable disable

namespace XLWebServices.Data.Migrations
{
    [DbContext(typeof(WsDbContext))]
    [Migration("20230506184334_PluginVersionStats")]
    partial class PluginVersionStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("XLWebServices.Data.Models.Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("XLWebServices.Data.Models.PluginVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Changelog")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiffLinesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiffLinesRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dip17Track")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsInitialRelease")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeToMerge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("PluginVersions");
                });

            modelBuilder.Entity("XLWebServices.Data.Models.PluginVersion", b =>
                {
                    b.HasOne("XLWebServices.Data.Models.Plugin", "Plugin")
                        .WithMany("VersionHistory")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("XLWebServices.Data.Models.Plugin", b =>
                {
                    b.Navigation("VersionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
